name: "Build FBX2GLTF"
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-build
  cancel-in-progress: true

jobs:
  build-win-10:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install conan
        run: |
          pip install --upgrade conan
        shell: bash

      - name: Setup conan profile
        run: |
          conan profile new default --detect
          conan profile show default
        shell: bash

      - name: Setup filter.lfs.required
        run: |
          git config --global filter.lfs.required false
        shell: bash

      - name: Setup filter.lfs.smudge
        run: |
          git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
        shell: bash

      - name: Setup filter.lfs.process
        run: |
          git config --global filter.lfs.process "git-lfs filter-process --skip"
        shell: bash
        
      - name: Fetch sdk
        run: |
          curl -O -L "https://github.com/V-Sekai/FBXSDK-Windows/archive/refs/tags/2020.2.zip"
        shell: cmd
            
      - name: install 7z extract
        run: |
          7z x 2020.2.zip
        shell: cmd

      - name: move
        run: |
          mkdir -p sdk
          mv ./FBXSDK-Windows-2020.2/sdk .
        shell: bash

      - name: Decompress sdk
        run: |
          zstd -d -r --rm ./sdk || true
        shell: bash

      - name: Conan install
        run: |
          conan install . -i build -s build_type=Release -s compiler="Visual Studio"
        shell: cmd

      - name: Conan build
        run: |
          conan build -bf build .
        shell: cmd

      - name: Run FBX2glTF help
        run: |
          ./build/Release/FBX2glTF.exe --help
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: FBX2glTF-windows.exe
          path: build/Release/FBX2glTF.exe

      - name: Copy licenses
        run: |
          mkdir -p result
          cp sdk/Windows/2020.2/License.rtf result/thirdparty-license.rtf
          cp LICENSE result/LICENSE
          cp build/Release/FBX2glTF.exe result/FBX2glTF.exe
        shell: bash

      - uses: papeloto/action-zip@v1
        with:
          files: result
          recursive: false
          dest: fbx2gltf-windows.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-windows
          prerelease: true
          title: FBX2glTF Windows packages
          files: |
            fbx2gltf-windows.zip
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install conan
        run: |
          pip install --upgrade conan
        shell: bash

      - name: Setup conan profile
        run: |
          conan profile new default --detect
          conan profile show default
        shell: bash

      - name: Setup filter.lfs.required
        run: |
          git config --global filter.lfs.required false
        shell: bash

      - name: Setup filter.lfs.smudge
        run: |
          git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
        shell: bash

      - name: Setup filter.lfs.process
        run: |
          git config --global filter.lfs.process "git-lfs filter-process --skip"
        shell: bash
        
      - name: Fetch sdk
        run: |
          curl -O -L "https://github.com/V-Sekai/FBXSDK-Linux/archive/refs/tags/2020.2.zip"
        shell: bash
            
      - name: install 7z extract
        run: |
          7z x 2020.2.zip
        shell: bash

      - name: move
        run: |
          mkdir -p sdk
          mv ./FBXSDK-Linux-2020.2/sdk .
        shell: bash

      - name: Decompress sdk
        run: |
          zstd -d -r --rm ./sdk || true
        shell: bash

      - name: Conan install
        run: |
          conan install . -i build -s build_type=Release --build fmt -s compiler.libcxx=libstdc++11
        shell: bash

      - name: Conan build
        run: |
          conan build -bf build .
        shell: bash

      - name: Run FBX2glTF help
        run: |
           ./build/FBX2glTF --help
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: FBX2glTF-linux
          path: build/FBX2glTF

      - name: Copy licenses
        run: |
          mkdir -p result
          cp sdk/Linux/2020.2/License.txt result/thirdparty-license.txt
          cp LICENSE result/LICENSE
          cp build/FBX2glTF result/FBX2glTF
        shell: bash

      - uses: papeloto/action-zip@v1
        with:
          files: result
          recursive: false
          dest: fbx2gltf-linux.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-linux
          prerelease: true
          title: FBX2glTF Linux packages
          files: |
            fbx2gltf-linux.zip

  build-macos-x86_64:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update python
        uses: actions/setup-python@v1
        
      - name: Install conan
        run: |
          pip install --upgrade conan
        shell: bash

      - name: Setup conan profile
        run: |
          conan profile new default --detect
          conan profile show default
        shell: bash

      - name: Setup filter.lfs.required
        run: |
          git config --global filter.lfs.required false
        shell: bash

      - name: Setup filter.lfs.smudge
        run: |
          git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
        shell: bash

      - name: Setup filter.lfs.process
        run: |
          git config --global filter.lfs.process "git-lfs filter-process --skip"
        shell: bash
        
      - name: Fetch sdk
        run: |
          curl -O -L "https://github.com/V-Sekai/FBXSDK-Darwin/archive/refs/tags/2020.2.zip"
        shell: bash
            
      - name: install 7z extract
        run: |
          7z x 2020.2.zip
        shell: bash

      - name: move
        run: |
          mkdir -p sdk
          mv ./FBXSDK-Darwin-2020.2/sdk .
        shell: bash

      - name: Decompress sdk
        run: |
          zstd -d -r --rm ./sdk || true
        shell: bash

      - name: Conan install
        run: |
          env CMAKE_OSX_ARCHITECTURES=x86_64 conan install . -i build -s build_type=Release --build missing --settings arch=x86_64
        shell: bash

      - name: Conan build
        run: |
          env CMAKE_OSX_ARCHITECTURES=x86_64 conan build -bf build .
        shell: bash

      - name: Run FBX2glTF help
        run: |
           ./build/FBX2glTF --help
        shell: bash

      - name: Adhoc signature
        run: |
           codesign -s - --options=runtime build/FBX2glTF
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: FBX2glTF-macos
          path: build/FBX2glTF

      - name: Copy licenses
        run: |
          mkdir -p result
          cp sdk/Darwin/2020.2/License.rtf result/thirdparty-license.rtf
          cp LICENSE result/LICENSE
          cp build/FBX2glTF result/FBX2glTF
        shell: bash

      - uses: papeloto/action-zip@v1
        with:
          files: result
          recursive: false
          dest: fbx2gltf-macos.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest-macos
          prerelease: true
          title: FBX2glTF Macos x86_64 packages
          files: |
            fbx2gltf-macos.zip
